### PR TITLE
Serialize

### PR DESCRIPTION
**Pull request by moezzie**
Added the Serialize() and Load() methods to enable networks to be save to any kind of storage and restored at a later time.

### CODE REVIEW

**Comment by jonhkr** [comment]
Thank you @moezzie.

I'm wondering whether we should implement the `Serialize/Load` methods or just document how one could do it.

**Comment by moezzie** [comment]
Yeah, that might be a good idea

**Comment by jonhkr** [comment]
Would you like to do that?

**Comment by moezzie** [comment]
Hey jonhkr,

Sorry for the delay, I'm a little short on time at the moment.
I'l send you a new PR this weekedn.

Cheers

**Comment by jonhkr** [comment]
No worries :smile: 
Take your time.

**Pull request closed without merging**
